name: First GHA HandsOn
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Build Frontend
        run: echo "Build React Frontend"

      - name: Check Date
        run: date

      - name: Call Secret
        run: echo "${{ secrets.KV_KEY }}"

      - name: Using Condition
        run: Call Secret
        if: github.event_name == 'push'
