name: Using Matrix Strategy

on:
  push:
    branches: [main]

jobs:
  compatibility-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
        environment: [Dev, Staging]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Script
        run: |
          echo " ${{ matrix.python-version }} in ${{ matrix.environment }} "
